# Main playbook
---

- name: Install prerequisites and user
  remote_user: deployment.user.id
  become: yes
  become_user: root
  become_method: sudo
  hosts: controllers, deployment[0]
  roles:
    - env
    - user

- name: Network configuration for controllers
  hosts: controllers
  remote_user: deployment.user.id
  # Parameters to roles defined as pre_tasks (could be inline, per role)
  pre_tasks:
    - set_fact:
        nodes: "{{ onos.controllers }}"
    - set_fact:
        type: "controller"
  roles:
    - net-iface-cfg
    - host-name

- name: Network configuration for clients
  hosts: clients
  remote_user: deployment.user.id
  # Parameters to roles defined as pre_tasks (could be inline, per role)
  pre_tasks:
    - set_fact:
        nodes: "{{ onos.clients }}"
    - set_fact:
        type: "client"
  roles:
    - net-iface-cfg
    - host-name

- name: Clone ONOS repo
  become_user: "{{ onos.user.id }}"
  become: yes
  hosts: deployment[0]
  vars:
    ansible_user: "{{ onos.user.id }}"
    ansible_ssh_pass: "{{ onos.user.pass }}"
  roles:
    - onos-git

- name: Clone SDXL2 repo
  become_user: "{{ onos.user.id }}"
  become: yes
  hosts: deployment[0]
  vars:
    ansible_user: "{{ onos.user.id }}"
    ansible_ssh_pass: "{{ onos.user.pass }}"
  roles:
    - onos-app-sdxl2

- name: Set-up ONOS cluster
  hosts: deployment[0]
  vars:
    ansible_user: "{{ onos.user.id }}"
    ansible_ssh_pass: "{{ onos.user.pass }}"
  roles:
    - onos-cluster
