# Install required packages
---

- import_tasks: install-java.yml

- name: Install other ONOS dependencies
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - git
    - zip
  become: yes
