# Define networking interfaces for end-to-end hosts
---

- import_tasks: host-config-name.yml
  vars:
    type: "client"
    nodes: "{{ onos.clients }}"

- import_tasks: iface-config-ip.yml
  vars:
    type: "client"
    nodes: "{{ onos.clients }}"

