# Define networking interfaces for controllers
---

- import_tasks: host-config-name.yml
  vars:
    type: "controller"
    nodes: "{{ onos.controllers }}"

- import_tasks: iface-config-ip.yml
  vars:
    type: "controller"
    nodes: "{{ onos.controllers }}"

