# Create "sdn" user
---

#- name: Include variables
#  include_vars:
#    file: ../../../inventories/production/group_vars/all
#    name: vars

- name: Create group for user running ONOS
  group:
    name: "{{ onos.group.id }}"
    state: present
  become: yes

- name: Create user to run ONOS and extend/append its groups with the above
  user:
    name: sdn
    shell: /bin/bash
    groups: "{{ onos.group.id }}"
    append: yes
  become: yes

- name: Allow above group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ onos.group.id }}"
    line: "%{{ onos.group.id }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  become: yes

- name: Add sudoer user to above group
  user:
    name: "{{ deployment.user.id }}"
    groups: "{{ onos.group.id }}"
    append: yes
    state: present
    createhome: yes
  become: yes

- name: Ensure SSH folder present for deployment user
  file:
    path: "/home/{{ deployment.user.id }}/.ssh"
    state: directory
    owner: "{{ deployment.user.id }}"
    group: "{{ deployment.user.id }}"
  become: yes

#- name: Copy SSH public key
#  copy:
#    src: "~/{{ deployment.user.key }}.pub"
#    dest: "/home/{{ deployment.user.id }}/.ssh/id_rsa_{{ deployment.user.id }}.pub"   
#    owner: "{{ deployment.user.id }}"
#    group: "{{ deployment.user.id }}"
#    force: true
#    mode: 0644

- name: Ensure SSH authorized_keys present
  file:
    path: "/home/{{ deployment.user.id }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ deployment.user.id }}"
    group: "{{ deployment.user.id }}"
    mode: 0644

#- name: Set up authorised keys for the deployer user
#  shell: |
#    cat "/home/{{ deployment.user.id }}/.ssh/id_rsa_{{ deployment.user.id }}.pub" >> /home/{{ deployment.user.id }}/.ssh/authorized_keys

- name: Set up authorised keys for the deployer user
  authorized_key:
    state: present
    user: "{{ deployment.user.id }}"
    key: "{{ item }}"
#  with_lines:
#    - "cat ~/.ssh/id_rsa_{{ deployment.user.id }}.pub"
  with_file:
    - "~/.ssh/id_rsa_onos_cluster.pub"
  become_user: "{{ deployment.user.id }}"
