# Clone ONOS repository and perform proper sources to load binaries
---

- name: Clone ONOS repository
  git:
    repo: https://gerrit.onosproject.org/onos
    dest: ~/onos
    version: onos-1.11
#    clone: yes
  become_user: sdn

- name: Source ONOS dev's bash_profile
  lineinfile:
    dest: ~/.bashrc
    state: present
    regexp: "^. ~/onos/tools/dev/bash_profile"
    line: ". ~/onos/tools/dev/bash_profile"
  become_user: sdn

#- name: Add sripts for SSH agent
#  become_user: sdn
#  blockinfile: |
#    dest: ~/.bashrc
#    backup: yes
#    block: |
#SSH_ENV="$HOME/.ssh/environment"
#function start_agent {
#    echo "Initialising new SSH agent..."
#    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
#    echo succeeded
#    chmod 600 "${SSH_ENV}"
#    . "${SSH_ENV}" > /dev/null
#    /usr/bin/ssh-add
#}
## Source SSH settings, if applicable
#if [ -f "${SSH_ENV}" ]; then
#    . "${SSH_ENV}" > /dev/null
#    #ps ${SSH_AGENT_PID} doesn't work under cywgin
#    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
#        start_agent;
#    }
#else
#    start_agent;
#fi

#- name: Add sripts for SSH agent
#  become_user: sdn
#  shell: |
#    cat << "EOF" >> ~/.bashrc
#
#SSH_ENV="$HOME/.ssh/environment"
#function start_agent {
#    echo "Initialising new SSH agent..."
#    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
#    echo succeeded
#    chmod 600 "${SSH_ENV}"
#    . "${SSH_ENV}" > /dev/null
#    /usr/bin/ssh-add
#}
## Source SSH settings, if applicable
#if [ -f "${SSH_ENV}" ]; then
#    . "${SSH_ENV}" > /dev/null
#    #ps ${SSH_AGENT_PID} doesn't work under cywgin
#    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
#        start_agent;
#    }
#else
#    start_agent;
#fi
#EOF
#  register: result

- name: Source bashrc
  shell: |
    . ~/.bashrc
  become_user: sdn
