# Define networking interfaces for controllers
---

- name: Configure data plane interfaces in hosts
  nmcli:
    ifname: "{{ name }}"
    ip4: "{{ ip }}"
    state: present
    when: name | search("eth")
    vars:
      name: "{{ iface | regex_replace(\"{(.*): u'(.*)'}\", \"\\1\") }}"
      # Filter addresses in list to just have the IP value
      ip: "{{ iface | regex_replace(\"{(.*): u'(.*)'}\", \"\\2\") }}"
      iface: "{{ item.1 }}"
   with_subelements:
     - "{{ onos.clients }}"
     - ip
