# Clone ONOS repository and load sources pointing to binaries
---

- name: Check for ONOS repository
  stat:
    path: ~/onos
  register: onos_repo

- name: Clone ONOS repository
  git:
    repo: https://gerrit.onosproject.org/onos
    dest: ~/onos
    version: "{{ onos.version }}"
    force: no
  when: onos_repo.stat.exists == False

- name: Ensure .bashrc exists
  file:
    path: ~/.bashrc
    state: touch

# Line must be added before non-interactivity SSH checks block any other command
- name: Source ONOS dev's bash_profile
  blockinfile:
    dest: ~/.bashrc
    state: present
    marker: "# {mark} ANSIBLE MANAGED BLOCK cell source (onos bash_profile)"
    insertbefore: BOF
    content: |
    
      # Source ONOS bash_profile before non-interactivity SSH checks block it (e.g. at EOF)
      . ~/onos/tools/dev/bash_profile

- import_tasks: ../../user/tasks/load-bashrc.yml
  vars:
    user: "{{ onos.user.id }}"

- name: Generate SSH keys for ONOS cluster (deploying) instance
  user:
    name: "{{ onos.user.id }}"
    generate_ssh_key: yes
